### ISSUE TITLE
Download error, Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by skmanzg** [premasagar/civitai-sync#1]
![image](https://github.com/premasagar/civitai-sync/assets/97992669/7de44715-54b3-42ec-98a7-5bc555f48ce4)

I wonder why does it happen?

(it worked well when I use download missing tho)

**Comment by premasagar** [comment]
Thanks. I think it is a failed response from the server, which might happen once every so often. The script sees the error and exits. If you run it again, it will probably work. Ideally the script would re-attempt, and exit after retrying, or retry periodically.

**Comment by skmanzg** [comment]
Yes. As you said, it worked well when I re-run it. I will close the issue but you may re-open this issue for others to see.
