### ISSUE TITLE
civitai's generations API returns raw images without metadata

### ISSUE THREAD

**Issue by duanemoody** [premasagar/civitai-sync#2]
I'm pleased the application has a parallel `data` directory with detailed, easy-to-read JSON in it, but the images we've been manually downloading embed most of the necessary metadata for prompting into the appropriate EXIF tag for JPEG/PNG where we can read it with utilities, search for prompt text, etc. 

Because Civitai's repo omits portions of the backend, I can't tell whether:
- Civitai only dynamically embeds the metadata when serving the image through its usual `https://orchestration.civitai.com/v1/consumer/images/{UUID}` endpoint, or 
- The metadata _is_ baked into the actual stored image data at generation time, but the TRPS API is actually stripping it (there appear to be functions for removing or not passing EXIF data)

Glancing over the (incomplete) Civitai codebase here without diving more deeply into it, either is possible.

**Comment by duanemoody** [comment]
I believe I was incorrect here, I'm seeing the metadata in the files now. Closing ticket.

**Comment by duanemoody** [comment]
I thought I was mistaken but the files with metadata came from another source.

**Comment by duanemoody** [comment]
I was in error here, the downloaded files are complete with metadata. My apologies.

**Comment by premasagar** [comment]
Thanks. Yes, Civitai embeds generation data (in the EXIF UserComment tag) at generation time. It's already there, when you download the images.
