### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by dfischer** [premasagar/civitai-sync#3]
YOU ARE A GOD SEND.

**Comment by premasagar** [comment]
Gratitude. It filled a need.

An official download option is being rolled out. I don't know if there's continued interest in a programmable pull approach to downloading generations. There are some other things it could do.

**Comment by Xevion** [comment]
You should probably close this issue, since it's more of just a public comment; nothing wrong with that since this isn't a highly trafficked repository, but there is not an 'issue' to be solved.
