### ISSUE TITLE
the download stopped working after the last civitai update

### ISSUE THREAD

**Issue by AxelExequielLuna** [premasagar/civitai-sync#4]
After the last update of civitai, the downloads stopped working, I know there is already an official way, but the tool is useful to download the generation data also in an organized way.

![Captura de pantalla_20240712_174126](https://github.com/user-attachments/assets/62d526b2-42b0-41ab-bb04-3de4e06f5fd6)

thank you so much I hope the development continues, this tool is awesome.

**Comment by premasagar** [comment]
civitai-sync has now been updated. The internal API endpoint for generation data had changed, because of the new features in the onsite generator.
Please see the tool page for migration details: https://civitai.com/models/526058
