### ISSUE TITLE
Error: No response for image

### ISSUE THREAD

**Issue by mukulyadav49** [premasagar/civitai-sync#5]
While downloading generations after the update using the API key, a lot of generations give a message:

`No response for image https://orchestration.civitai.com/v2/consumer/blobs/6RP0BQF-----------------

No response for image https://orchestration.civitai.com/v2/consumer/blobs/R------`

And I don't know if it's an issue from CivitAI's end or the downloader.

Edit: Edited for better readability, hidden the keys in URL for privacy.

**Comment by premasagar** [comment]
I believe these were images that you would have deleted in the on-site generator, and they were still present in the data feed, but could not be downloaded. This was a bug that was fixed.
