### ISSUE TITLE
Ignores text-to-image hi-res fix but not image-to-image hi-res fix

### ISSUE THREAD

**Issue by xion2** [premasagar/civitai-sync#6]
The title pretty much says it all. 

Image-to-image hi-res fix generations are download normally, they aren't created in pairs. Text-to-image hi-res fix generations are only partially downloaded, specifically the low-res image of the pair.

It should be reproducible unless there is something specific on my machine that is causing this issue.

**Comment by premasagar** [comment]
This is fixed in version 3.0.3, which updates the downloaded media filenames to accommodate upscaled images.

Use "Download options" > "Update media filenames" to rename previously downloaded images to the latest format.
Use "Download options" > "Download missing" to download any missing images.
